apiVersion: apps/v1
kind: Deployment
metadata:
  name: movies-parser
  namespace: watchlist
spec:
  selector:
    matchLabels:
      app: movies-parser
  template:
    metadata: 
      labels: 
        app: movies-parser
    spec:
      containers:
      - name: movies-parser
        image: 982039600869.dkr.ecr.eu-central-1.amazonaws.com/stephnangue/movies-parser:develop
        env:
        - name: AWS_REGION
          value: eu-central-1
        - name: SQS_URL
          value: https://sqs.eu-central-1.amazonaws.com/982039600869/movies_to_parse_sandbox
        - name: MONGO_DATABASE
          valueFrom:
            secretKeyRef:
              name: mongodb-access
              key: database
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: mongodb-access
              key: uri