apiVersion: apps/v1
kind: Deployment
metadata:
  name: movies-marketplace
  namespace: watchlist
spec:
  selector:
    matchLabels:
      app: movies-marketplace
  template:
    metadata: 
      labels: 
        app: movies-marketplace
    spec:
      containers:
      - name: movies-marketplace
        image: 982039600869.dkr.ecr.eu-central-1.amazonaws.com/stephnangue/movies-marketplace:develop
        ports:
        - containerPort: 80